/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mkalugin_keychain_KeyChain */

#ifndef _Included_com_mkalugin_keychain_KeyChain
#define _Included_com_mkalugin_keychain_KeyChain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mkalugin_keychain_KeyChain
 * Method:    StorePasswordInKeychain
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mkalugin_keychain_KeyChain_StorePasswordInKeychain
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_mkalugin_keychain_KeyChain
 * Method:    GetPasswordFromKeychain
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mkalugin_keychain_KeyChain_GetPasswordFromKeychain
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
